# Generated by Django 2.0.2 on 2019-07-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190713_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
